### ISSUE TITLE
Fail to run the game

### ISSUE THREAD

**Issue by bregman-arie** [bnoland/asteroids#1]
I get the following error:

  File "asteroids.py", line 300
    print('Error: pygame font module unavailable.', file=sys.stderr)
                                                        ^
SyntaxError: invalid syntax

**Comment by bnoland** [comment]
I have a suspicion you may be trying to run it under Python 2.x. The program was created using Python 3.5. The syntax for the print statement is different under Python 3.x than in Python 2.x, and I figure this is what's giving you the error.

**Comment by bnoland** [comment]
Also, it just occurred to me that this particular line of code isn't even parsed by the interpreter unless the statement "not pygame.font" evaluates to True. So, in addition to the issue above, it seems that for whatever reason the pygame font module is unavailable (it's an optional module). See here for more details: http://pygame.org/docs/ref/font.html
